In [1]:
from ebmdatalab import bq
import os

In [2]:
sql = '''WITH bnf_codes AS (
  SELECT bnf_code FROM hscic.presentation WHERE 
  bnf_code LIKE '1001010%' #bnf section non-steroidal anti-inflammatory drugs
  )

SELECT "vmp" AS type, id, bnf_code, nm
FROM dmd.vmp
WHERE bnf_code IN (SELECT * FROM bnf_codes)

UNION ALL

SELECT "amp" AS type, id, bnf_code, descr
FROM dmd.amp
WHERE bnf_code IN (SELECT * FROM bnf_codes)

ORDER BY type, bnf_code, id'''

nsaid_codelist = bq.cached_read(sql, csv_path=os.path.join('..','data','nsaid_codelist.csv'))
nsaid_codelist.head(10)

,type,id,bnf_code,nm
0,amp,92511000001106,100101040AAAAAA,Tenoxicam 20mg tablets (A A H Pharmaceuticals ...
1,amp,565511000001103,100101040AAAAAA,Tenoxicam 20mg tablets (Sandoz Ltd)
2,amp,602711000001108,100101040AAAAAA,Tenoxicam 20mg tablets (Alliance Healthcare (D...
3,amp,753111000001104,100101040AAAAAA,Tenoxicam 20mg tablets (Kent Pharmaceuticals Ltd)
4,amp,15229011000001105,100101040AAAAAA,Tenoxicam 20mg tablets (Sigma Pharmaceuticals ...
5,amp,21786211000001109,100101040AAAAAA,Tenoxicam 20mg tablets (Waymade Healthcare Plc)
6,amp,14946111000001109,100101040AAADAD,Tenoxicam 20mg powder and solvent for solution...
7,amp,15023011000001101,100101040AAADAD,Tenoxicam 20mg powder and solvent for solution...
8,amp,15151911000001109,100101040AAADAD,Tenoxicam 20mg powder and solvent for solution...
9,amp,213111000001102,100101040BBAAAA,Mobiflex 20mg tablets (Mylan)

In [3]:
nsaid_codelist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1235 entries, 0 to 1234
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   type      1235 non-null   object
 1   id        1235 non-null   int64
 2   bnf_code  1235 non-null   object
 3   nm        1235 non-null   object
dtypes: int64(1), object(3)
memory usage: 38.7+ KB